version: "3.8"

services:
  # Backend Service
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: todo-backend
    env_file:
      - .env
    ports:
      - "3002:3002"
    networks:
      - todo-network
    restart: unless-stopped
networks:
  todo-network:
    driver: bridge
